# Generated by Django 4.2.16 on 2024-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deletedstudent_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='9E02CB1A', max_length=100, unique=True),
        ),
    ]
